// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KeyGenPhase1Msg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	PubKeyCommit         []byte   `protobuf:"bytes,2,opt,name=pub_key_commit,json=pubKeyCommit,proto3" json:"pub_key_commit,omitempty"`
	CofCommit            [][]byte `protobuf:"bytes,3,rep,name=cof_commit,json=cofCommit,proto3" json:"cof_commit,omitempty"`
	NTilde               []byte   `protobuf:"bytes,4,opt,name=NTilde,proto3" json:"NTilde,omitempty"`
	H1                   []byte   `protobuf:"bytes,5,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   []byte   `protobuf:"bytes,6,opt,name=h2,proto3" json:"h2,omitempty"`
	Proof                *PQProof `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`
	ShamirSharePubKey    []byte   `protobuf:"bytes,8,opt,name=shamir_share_pub_key,json=shamirSharePubKey,proto3" json:"shamir_share_pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyGenPhase1Msg) Reset()         { *m = KeyGenPhase1Msg{} }
func (m *KeyGenPhase1Msg) String() string { return proto.CompactTextString(m) }
func (*KeyGenPhase1Msg) ProtoMessage()    {}
func (*KeyGenPhase1Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *KeyGenPhase1Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenPhase1Msg.Unmarshal(m, b)
}
func (m *KeyGenPhase1Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenPhase1Msg.Marshal(b, m, deterministic)
}
func (m *KeyGenPhase1Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenPhase1Msg.Merge(m, src)
}
func (m *KeyGenPhase1Msg) XXX_Size() int {
	return xxx_messageInfo_KeyGenPhase1Msg.Size(m)
}
func (m *KeyGenPhase1Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenPhase1Msg.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenPhase1Msg proto.InternalMessageInfo

func (m *KeyGenPhase1Msg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeyGenPhase1Msg) GetPubKeyCommit() []byte {
	if m != nil {
		return m.PubKeyCommit
	}
	return nil
}

func (m *KeyGenPhase1Msg) GetCofCommit() [][]byte {
	if m != nil {
		return m.CofCommit
	}
	return nil
}

func (m *KeyGenPhase1Msg) GetNTilde() []byte {
	if m != nil {
		return m.NTilde
	}
	return nil
}

func (m *KeyGenPhase1Msg) GetH1() []byte {
	if m != nil {
		return m.H1
	}
	return nil
}

func (m *KeyGenPhase1Msg) GetH2() []byte {
	if m != nil {
		return m.H2
	}
	return nil
}

func (m *KeyGenPhase1Msg) GetProof() *PQProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *KeyGenPhase1Msg) GetShamirSharePubKey() []byte {
	if m != nil {
		return m.ShamirSharePubKey
	}
	return nil
}

type KeyGenPhase2Msg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	LabelTo              string   `protobuf:"bytes,2,opt,name=label_to,json=labelTo,proto3" json:"label_to,omitempty"`
	Share                *ShareXY `protobuf:"bytes,3,opt,name=share,proto3" json:"share,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	BlindFactor          []byte   `protobuf:"bytes,5,opt,name=blind_factor,json=blindFactor,proto3" json:"blind_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyGenPhase2Msg) Reset()         { *m = KeyGenPhase2Msg{} }
func (m *KeyGenPhase2Msg) String() string { return proto.CompactTextString(m) }
func (*KeyGenPhase2Msg) ProtoMessage()    {}
func (*KeyGenPhase2Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *KeyGenPhase2Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenPhase2Msg.Unmarshal(m, b)
}
func (m *KeyGenPhase2Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenPhase2Msg.Marshal(b, m, deterministic)
}
func (m *KeyGenPhase2Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenPhase2Msg.Merge(m, src)
}
func (m *KeyGenPhase2Msg) XXX_Size() int {
	return xxx_messageInfo_KeyGenPhase2Msg.Size(m)
}
func (m *KeyGenPhase2Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenPhase2Msg.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenPhase2Msg proto.InternalMessageInfo

func (m *KeyGenPhase2Msg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeyGenPhase2Msg) GetLabelTo() string {
	if m != nil {
		return m.LabelTo
	}
	return ""
}

func (m *KeyGenPhase2Msg) GetShare() *ShareXY {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *KeyGenPhase2Msg) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *KeyGenPhase2Msg) GetBlindFactor() []byte {
	if m != nil {
		return m.BlindFactor
	}
	return nil
}

type KeyGenPhase3Msg struct {
	LabelFrom            string        `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	ShamirPub            []byte        `protobuf:"bytes,2,opt,name=shamir_pub,json=shamirPub,proto3" json:"shamir_pub,omitempty"`
	Proof                *SchnorrProof `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KeyGenPhase3Msg) Reset()         { *m = KeyGenPhase3Msg{} }
func (m *KeyGenPhase3Msg) String() string { return proto.CompactTextString(m) }
func (*KeyGenPhase3Msg) ProtoMessage()    {}
func (*KeyGenPhase3Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *KeyGenPhase3Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenPhase3Msg.Unmarshal(m, b)
}
func (m *KeyGenPhase3Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenPhase3Msg.Marshal(b, m, deterministic)
}
func (m *KeyGenPhase3Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenPhase3Msg.Merge(m, src)
}
func (m *KeyGenPhase3Msg) XXX_Size() int {
	return xxx_messageInfo_KeyGenPhase3Msg.Size(m)
}
func (m *KeyGenPhase3Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenPhase3Msg.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenPhase3Msg proto.InternalMessageInfo

func (m *KeyGenPhase3Msg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeyGenPhase3Msg) GetShamirPub() []byte {
	if m != nil {
		return m.ShamirPub
	}
	return nil
}

func (m *KeyGenPhase3Msg) GetProof() *SchnorrProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type KeySignPhase1Msg struct {
	LabelFrom            string               `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	LabelTo              string               `protobuf:"bytes,2,opt,name=label_to,json=labelTo,proto3" json:"label_to,omitempty"`
	MessageK             []byte               `protobuf:"bytes,3,opt,name=message_k,json=messageK,proto3" json:"message_k,omitempty"`
	MessageR             []byte               `protobuf:"bytes,4,opt,name=message_r,json=messageR,proto3" json:"message_r,omitempty"`
	SigOthersRCommit     []byte               `protobuf:"bytes,5,opt,name=sig_others_r_commit,json=sigOthersRCommit,proto3" json:"sig_others_r_commit,omitempty"`
	PaillierPubKey       *PaillierPubKey      `protobuf:"bytes,6,opt,name=paillier_pubKey,json=paillierPubKey,proto3" json:"paillier_pubKey,omitempty"`
	PaillierRangeProofK  *InitiatorRangeProof `protobuf:"bytes,7,opt,name=paillier_range_proof_k,json=paillierRangeProofK,proto3" json:"paillier_range_proof_k,omitempty"`
	PaillierRangeProofR  *InitiatorRangeProof `protobuf:"bytes,8,opt,name=paillier_range_proof_r,json=paillierRangeProofR,proto3" json:"paillier_range_proof_r,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KeySignPhase1Msg) Reset()         { *m = KeySignPhase1Msg{} }
func (m *KeySignPhase1Msg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase1Msg) ProtoMessage()    {}
func (*KeySignPhase1Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *KeySignPhase1Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase1Msg.Unmarshal(m, b)
}
func (m *KeySignPhase1Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase1Msg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase1Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase1Msg.Merge(m, src)
}
func (m *KeySignPhase1Msg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase1Msg.Size(m)
}
func (m *KeySignPhase1Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase1Msg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase1Msg proto.InternalMessageInfo

func (m *KeySignPhase1Msg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase1Msg) GetLabelTo() string {
	if m != nil {
		return m.LabelTo
	}
	return ""
}

func (m *KeySignPhase1Msg) GetMessageK() []byte {
	if m != nil {
		return m.MessageK
	}
	return nil
}

func (m *KeySignPhase1Msg) GetMessageR() []byte {
	if m != nil {
		return m.MessageR
	}
	return nil
}

func (m *KeySignPhase1Msg) GetSigOthersRCommit() []byte {
	if m != nil {
		return m.SigOthersRCommit
	}
	return nil
}

func (m *KeySignPhase1Msg) GetPaillierPubKey() *PaillierPubKey {
	if m != nil {
		return m.PaillierPubKey
	}
	return nil
}

func (m *KeySignPhase1Msg) GetPaillierRangeProofK() *InitiatorRangeProof {
	if m != nil {
		return m.PaillierRangeProofK
	}
	return nil
}

func (m *KeySignPhase1Msg) GetPaillierRangeProofR() *InitiatorRangeProof {
	if m != nil {
		return m.PaillierRangeProofR
	}
	return nil
}

type KeySignPhase2Msg struct {
	LabelFrom            string               `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	LabelTo              string               `protobuf:"bytes,2,opt,name=label_to,json=labelTo,proto3" json:"label_to,omitempty"`
	MessageKResponse     []byte               `protobuf:"bytes,3,opt,name=message_k_response,json=messageKResponse,proto3" json:"message_k_response,omitempty"`
	MessageRResponse     []byte               `protobuf:"bytes,4,opt,name=message_r_response,json=messageRResponse,proto3" json:"message_r_response,omitempty"`
	PaillierRangeProofK  *ResponderRangeProof `protobuf:"bytes,5,opt,name=paillier_range_proof_k,json=paillierRangeProofK,proto3" json:"paillier_range_proof_k,omitempty"`
	PaillierRangeProofR  *ResponderRangeProof `protobuf:"bytes,6,opt,name=paillier_range_proof_r,json=paillierRangeProofR,proto3" json:"paillier_range_proof_r,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *KeySignPhase2Msg) Reset()         { *m = KeySignPhase2Msg{} }
func (m *KeySignPhase2Msg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase2Msg) ProtoMessage()    {}
func (*KeySignPhase2Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *KeySignPhase2Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase2Msg.Unmarshal(m, b)
}
func (m *KeySignPhase2Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase2Msg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase2Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase2Msg.Merge(m, src)
}
func (m *KeySignPhase2Msg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase2Msg.Size(m)
}
func (m *KeySignPhase2Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase2Msg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase2Msg proto.InternalMessageInfo

func (m *KeySignPhase2Msg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase2Msg) GetLabelTo() string {
	if m != nil {
		return m.LabelTo
	}
	return ""
}

func (m *KeySignPhase2Msg) GetMessageKResponse() []byte {
	if m != nil {
		return m.MessageKResponse
	}
	return nil
}

func (m *KeySignPhase2Msg) GetMessageRResponse() []byte {
	if m != nil {
		return m.MessageRResponse
	}
	return nil
}

func (m *KeySignPhase2Msg) GetPaillierRangeProofK() *ResponderRangeProof {
	if m != nil {
		return m.PaillierRangeProofK
	}
	return nil
}

func (m *KeySignPhase2Msg) GetPaillierRangeProofR() *ResponderRangeProof {
	if m != nil {
		return m.PaillierRangeProofR
	}
	return nil
}

type KeySignPhase3And4Msg struct {
	LabelFrom            string        `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	Thea                 []byte        `protobuf:"bytes,2,opt,name=thea,proto3" json:"thea,omitempty"`
	KiProof              *SchnorrProof `protobuf:"bytes,3,opt,name=ki_proof,json=kiProof,proto3" json:"ki_proof,omitempty"`
	SigOthersR           *SigR         `protobuf:"bytes,4,opt,name=sig_others_r,json=sigOthersR,proto3" json:"sig_others_r,omitempty"`
	BlindFactor          []byte        `protobuf:"bytes,5,opt,name=blind_factor,json=blindFactor,proto3" json:"blind_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KeySignPhase3And4Msg) Reset()         { *m = KeySignPhase3And4Msg{} }
func (m *KeySignPhase3And4Msg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase3And4Msg) ProtoMessage()    {}
func (*KeySignPhase3And4Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *KeySignPhase3And4Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase3And4Msg.Unmarshal(m, b)
}
func (m *KeySignPhase3And4Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase3And4Msg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase3And4Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase3And4Msg.Merge(m, src)
}
func (m *KeySignPhase3And4Msg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase3And4Msg.Size(m)
}
func (m *KeySignPhase3And4Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase3And4Msg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase3And4Msg proto.InternalMessageInfo

func (m *KeySignPhase3And4Msg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase3And4Msg) GetThea() []byte {
	if m != nil {
		return m.Thea
	}
	return nil
}

func (m *KeySignPhase3And4Msg) GetKiProof() *SchnorrProof {
	if m != nil {
		return m.KiProof
	}
	return nil
}

func (m *KeySignPhase3And4Msg) GetSigOthersR() *SigR {
	if m != nil {
		return m.SigOthersR
	}
	return nil
}

func (m *KeySignPhase3And4Msg) GetBlindFactor() []byte {
	if m != nil {
		return m.BlindFactor
	}
	return nil
}

type KeySignPhase5AMsg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	VCommit              []byte   `protobuf:"bytes,2,opt,name=v_commit,json=vCommit,proto3" json:"v_commit,omitempty"`
	ACommit              []byte   `protobuf:"bytes,3,opt,name=a_commit,json=aCommit,proto3" json:"a_commit,omitempty"`
	BCommit              []byte   `protobuf:"bytes,4,opt,name=b_commit,json=bCommit,proto3" json:"b_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeySignPhase5AMsg) Reset()         { *m = KeySignPhase5AMsg{} }
func (m *KeySignPhase5AMsg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase5AMsg) ProtoMessage()    {}
func (*KeySignPhase5AMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *KeySignPhase5AMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase5AMsg.Unmarshal(m, b)
}
func (m *KeySignPhase5AMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase5AMsg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase5AMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase5AMsg.Merge(m, src)
}
func (m *KeySignPhase5AMsg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase5AMsg.Size(m)
}
func (m *KeySignPhase5AMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase5AMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase5AMsg proto.InternalMessageInfo

func (m *KeySignPhase5AMsg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase5AMsg) GetVCommit() []byte {
	if m != nil {
		return m.VCommit
	}
	return nil
}

func (m *KeySignPhase5AMsg) GetACommit() []byte {
	if m != nil {
		return m.ACommit
	}
	return nil
}

func (m *KeySignPhase5AMsg) GetBCommit() []byte {
	if m != nil {
		return m.BCommit
	}
	return nil
}

type KeySignPhase5BMsg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	Proof                *SiProof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	VBlindFactor         []byte   `protobuf:"bytes,3,opt,name=v_blind_factor,json=vBlindFactor,proto3" json:"v_blind_factor,omitempty"`
	ABlindFactor         []byte   `protobuf:"bytes,4,opt,name=a_blind_factor,json=aBlindFactor,proto3" json:"a_blind_factor,omitempty"`
	BBlindFactor         []byte   `protobuf:"bytes,5,opt,name=b_blind_factor,json=bBlindFactor,proto3" json:"b_blind_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeySignPhase5BMsg) Reset()         { *m = KeySignPhase5BMsg{} }
func (m *KeySignPhase5BMsg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase5BMsg) ProtoMessage()    {}
func (*KeySignPhase5BMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *KeySignPhase5BMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase5BMsg.Unmarshal(m, b)
}
func (m *KeySignPhase5BMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase5BMsg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase5BMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase5BMsg.Merge(m, src)
}
func (m *KeySignPhase5BMsg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase5BMsg.Size(m)
}
func (m *KeySignPhase5BMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase5BMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase5BMsg proto.InternalMessageInfo

func (m *KeySignPhase5BMsg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase5BMsg) GetProof() *SiProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *KeySignPhase5BMsg) GetVBlindFactor() []byte {
	if m != nil {
		return m.VBlindFactor
	}
	return nil
}

func (m *KeySignPhase5BMsg) GetABlindFactor() []byte {
	if m != nil {
		return m.ABlindFactor
	}
	return nil
}

func (m *KeySignPhase5BMsg) GetBBlindFactor() []byte {
	if m != nil {
		return m.BBlindFactor
	}
	return nil
}

type KeySignPhase5CMsg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	UCommit              []byte   `protobuf:"bytes,2,opt,name=u_commit,json=uCommit,proto3" json:"u_commit,omitempty"`
	TCommit              []byte   `protobuf:"bytes,3,opt,name=t_commit,json=tCommit,proto3" json:"t_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeySignPhase5CMsg) Reset()         { *m = KeySignPhase5CMsg{} }
func (m *KeySignPhase5CMsg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase5CMsg) ProtoMessage()    {}
func (*KeySignPhase5CMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *KeySignPhase5CMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase5CMsg.Unmarshal(m, b)
}
func (m *KeySignPhase5CMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase5CMsg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase5CMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase5CMsg.Merge(m, src)
}
func (m *KeySignPhase5CMsg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase5CMsg.Size(m)
}
func (m *KeySignPhase5CMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase5CMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase5CMsg proto.InternalMessageInfo

func (m *KeySignPhase5CMsg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase5CMsg) GetUCommit() []byte {
	if m != nil {
		return m.UCommit
	}
	return nil
}

func (m *KeySignPhase5CMsg) GetTCommit() []byte {
	if m != nil {
		return m.TCommit
	}
	return nil
}

type KeySignPhase5DMsg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	Check                *SiCheck `protobuf:"bytes,2,opt,name=check,proto3" json:"check,omitempty"`
	UBlindFactor         []byte   `protobuf:"bytes,3,opt,name=u_blind_factor,json=uBlindFactor,proto3" json:"u_blind_factor,omitempty"`
	TBlindFactor         []byte   `protobuf:"bytes,4,opt,name=t_blind_factor,json=tBlindFactor,proto3" json:"t_blind_factor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeySignPhase5DMsg) Reset()         { *m = KeySignPhase5DMsg{} }
func (m *KeySignPhase5DMsg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase5DMsg) ProtoMessage()    {}
func (*KeySignPhase5DMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *KeySignPhase5DMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase5DMsg.Unmarshal(m, b)
}
func (m *KeySignPhase5DMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase5DMsg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase5DMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase5DMsg.Merge(m, src)
}
func (m *KeySignPhase5DMsg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase5DMsg.Size(m)
}
func (m *KeySignPhase5DMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase5DMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase5DMsg proto.InternalMessageInfo

func (m *KeySignPhase5DMsg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase5DMsg) GetCheck() *SiCheck {
	if m != nil {
		return m.Check
	}
	return nil
}

func (m *KeySignPhase5DMsg) GetUBlindFactor() []byte {
	if m != nil {
		return m.UBlindFactor
	}
	return nil
}

func (m *KeySignPhase5DMsg) GetTBlindFactor() []byte {
	if m != nil {
		return m.TBlindFactor
	}
	return nil
}

type KeySignPhase5EMsg struct {
	LabelFrom            string   `protobuf:"bytes,1,opt,name=label_from,json=labelFrom,proto3" json:"label_from,omitempty"`
	Sigr                 []byte   `protobuf:"bytes,2,opt,name=sigr,proto3" json:"sigr,omitempty"`
	Sigs                 []byte   `protobuf:"bytes,3,opt,name=sigs,proto3" json:"sigs,omitempty"`
	V                    []byte   `protobuf:"bytes,4,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeySignPhase5EMsg) Reset()         { *m = KeySignPhase5EMsg{} }
func (m *KeySignPhase5EMsg) String() string { return proto.CompactTextString(m) }
func (*KeySignPhase5EMsg) ProtoMessage()    {}
func (*KeySignPhase5EMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *KeySignPhase5EMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeySignPhase5EMsg.Unmarshal(m, b)
}
func (m *KeySignPhase5EMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeySignPhase5EMsg.Marshal(b, m, deterministic)
}
func (m *KeySignPhase5EMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeySignPhase5EMsg.Merge(m, src)
}
func (m *KeySignPhase5EMsg) XXX_Size() int {
	return xxx_messageInfo_KeySignPhase5EMsg.Size(m)
}
func (m *KeySignPhase5EMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_KeySignPhase5EMsg.DiscardUnknown(m)
}

var xxx_messageInfo_KeySignPhase5EMsg proto.InternalMessageInfo

func (m *KeySignPhase5EMsg) GetLabelFrom() string {
	if m != nil {
		return m.LabelFrom
	}
	return ""
}

func (m *KeySignPhase5EMsg) GetSigr() []byte {
	if m != nil {
		return m.Sigr
	}
	return nil
}

func (m *KeySignPhase5EMsg) GetSigs() []byte {
	if m != nil {
		return m.Sigs
	}
	return nil
}

func (m *KeySignPhase5EMsg) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

type SigR struct {
	X                    []byte   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigR) Reset()         { *m = SigR{} }
func (m *SigR) String() string { return proto.CompactTextString(m) }
func (*SigR) ProtoMessage()    {}
func (*SigR) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *SigR) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigR.Unmarshal(m, b)
}
func (m *SigR) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigR.Marshal(b, m, deterministic)
}
func (m *SigR) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigR.Merge(m, src)
}
func (m *SigR) XXX_Size() int {
	return xxx_messageInfo_SigR.Size(m)
}
func (m *SigR) XXX_DiscardUnknown() {
	xxx_messageInfo_SigR.DiscardUnknown(m)
}

var xxx_messageInfo_SigR proto.InternalMessageInfo

func (m *SigR) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *SigR) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type ShareXY struct {
	X                    []byte   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    []byte   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareXY) Reset()         { *m = ShareXY{} }
func (m *ShareXY) String() string { return proto.CompactTextString(m) }
func (*ShareXY) ProtoMessage()    {}
func (*ShareXY) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *ShareXY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareXY.Unmarshal(m, b)
}
func (m *ShareXY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareXY.Marshal(b, m, deterministic)
}
func (m *ShareXY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareXY.Merge(m, src)
}
func (m *ShareXY) XXX_Size() int {
	return xxx_messageInfo_ShareXY.Size(m)
}
func (m *ShareXY) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareXY.DiscardUnknown(m)
}

var xxx_messageInfo_ShareXY proto.InternalMessageInfo

func (m *ShareXY) GetX() []byte {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *ShareXY) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type PaillierPubKey struct {
	Len                  int64    `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	N                    []byte   `protobuf:"bytes,2,opt,name=n,proto3" json:"n,omitempty"`
	G                    []byte   `protobuf:"bytes,3,opt,name=g,proto3" json:"g,omitempty"`
	Nsq                  []byte   `protobuf:"bytes,4,opt,name=nsq,proto3" json:"nsq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaillierPubKey) Reset()         { *m = PaillierPubKey{} }
func (m *PaillierPubKey) String() string { return proto.CompactTextString(m) }
func (*PaillierPubKey) ProtoMessage()    {}
func (*PaillierPubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *PaillierPubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaillierPubKey.Unmarshal(m, b)
}
func (m *PaillierPubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaillierPubKey.Marshal(b, m, deterministic)
}
func (m *PaillierPubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaillierPubKey.Merge(m, src)
}
func (m *PaillierPubKey) XXX_Size() int {
	return xxx_messageInfo_PaillierPubKey.Size(m)
}
func (m *PaillierPubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PaillierPubKey.DiscardUnknown(m)
}

var xxx_messageInfo_PaillierPubKey proto.InternalMessageInfo

func (m *PaillierPubKey) GetLen() int64 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *PaillierPubKey) GetN() []byte {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *PaillierPubKey) GetG() []byte {
	if m != nil {
		return m.G
	}
	return nil
}

func (m *PaillierPubKey) GetNsq() []byte {
	if m != nil {
		return m.Nsq
	}
	return nil
}

type InitiatorRangeProof struct {
	Z                    []byte   `protobuf:"bytes,1,opt,name=z,proto3" json:"z,omitempty"`
	W                    []byte   `protobuf:"bytes,2,opt,name=w,proto3" json:"w,omitempty"`
	Mu                   []byte   `protobuf:"bytes,3,opt,name=mu,proto3" json:"mu,omitempty"`
	S                    []byte   `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	S1                   []byte   `protobuf:"bytes,5,opt,name=s1,proto3" json:"s1,omitempty"`
	S2                   []byte   `protobuf:"bytes,6,opt,name=s2,proto3" json:"s2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitiatorRangeProof) Reset()         { *m = InitiatorRangeProof{} }
func (m *InitiatorRangeProof) String() string { return proto.CompactTextString(m) }
func (*InitiatorRangeProof) ProtoMessage()    {}
func (*InitiatorRangeProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *InitiatorRangeProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitiatorRangeProof.Unmarshal(m, b)
}
func (m *InitiatorRangeProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitiatorRangeProof.Marshal(b, m, deterministic)
}
func (m *InitiatorRangeProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitiatorRangeProof.Merge(m, src)
}
func (m *InitiatorRangeProof) XXX_Size() int {
	return xxx_messageInfo_InitiatorRangeProof.Size(m)
}
func (m *InitiatorRangeProof) XXX_DiscardUnknown() {
	xxx_messageInfo_InitiatorRangeProof.DiscardUnknown(m)
}

var xxx_messageInfo_InitiatorRangeProof proto.InternalMessageInfo

func (m *InitiatorRangeProof) GetZ() []byte {
	if m != nil {
		return m.Z
	}
	return nil
}

func (m *InitiatorRangeProof) GetW() []byte {
	if m != nil {
		return m.W
	}
	return nil
}

func (m *InitiatorRangeProof) GetMu() []byte {
	if m != nil {
		return m.Mu
	}
	return nil
}

func (m *InitiatorRangeProof) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *InitiatorRangeProof) GetS1() []byte {
	if m != nil {
		return m.S1
	}
	return nil
}

func (m *InitiatorRangeProof) GetS2() []byte {
	if m != nil {
		return m.S2
	}
	return nil
}

type ResponderRangeProof struct {
	MuX                  []byte   `protobuf:"bytes,1,opt,name=mu_x,json=muX,proto3" json:"mu_x,omitempty"`
	MuY                  []byte   `protobuf:"bytes,2,opt,name=mu_y,json=muY,proto3" json:"mu_y,omitempty"`
	Z                    []byte   `protobuf:"bytes,3,opt,name=z,proto3" json:"z,omitempty"`
	ZD                   []byte   `protobuf:"bytes,4,opt,name=z_d,json=zD,proto3" json:"z_d,omitempty"`
	T                    []byte   `protobuf:"bytes,5,opt,name=t,proto3" json:"t,omitempty"`
	V                    []byte   `protobuf:"bytes,6,opt,name=v,proto3" json:"v,omitempty"`
	W                    []byte   `protobuf:"bytes,7,opt,name=w,proto3" json:"w,omitempty"`
	S                    []byte   `protobuf:"bytes,8,opt,name=s,proto3" json:"s,omitempty"`
	S1                   []byte   `protobuf:"bytes,9,opt,name=s1,proto3" json:"s1,omitempty"`
	S2                   []byte   `protobuf:"bytes,10,opt,name=s2,proto3" json:"s2,omitempty"`
	T1                   []byte   `protobuf:"bytes,11,opt,name=t1,proto3" json:"t1,omitempty"`
	T2                   []byte   `protobuf:"bytes,12,opt,name=t2,proto3" json:"t2,omitempty"`
	XX                   []byte   `protobuf:"bytes,13,opt,name=x_x,json=xX,proto3" json:"x_x,omitempty"`
	XY                   []byte   `protobuf:"bytes,14,opt,name=x_y,json=xY,proto3" json:"x_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponderRangeProof) Reset()         { *m = ResponderRangeProof{} }
func (m *ResponderRangeProof) String() string { return proto.CompactTextString(m) }
func (*ResponderRangeProof) ProtoMessage()    {}
func (*ResponderRangeProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *ResponderRangeProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponderRangeProof.Unmarshal(m, b)
}
func (m *ResponderRangeProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponderRangeProof.Marshal(b, m, deterministic)
}
func (m *ResponderRangeProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponderRangeProof.Merge(m, src)
}
func (m *ResponderRangeProof) XXX_Size() int {
	return xxx_messageInfo_ResponderRangeProof.Size(m)
}
func (m *ResponderRangeProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponderRangeProof.DiscardUnknown(m)
}

var xxx_messageInfo_ResponderRangeProof proto.InternalMessageInfo

func (m *ResponderRangeProof) GetMuX() []byte {
	if m != nil {
		return m.MuX
	}
	return nil
}

func (m *ResponderRangeProof) GetMuY() []byte {
	if m != nil {
		return m.MuY
	}
	return nil
}

func (m *ResponderRangeProof) GetZ() []byte {
	if m != nil {
		return m.Z
	}
	return nil
}

func (m *ResponderRangeProof) GetZD() []byte {
	if m != nil {
		return m.ZD
	}
	return nil
}

func (m *ResponderRangeProof) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *ResponderRangeProof) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *ResponderRangeProof) GetW() []byte {
	if m != nil {
		return m.W
	}
	return nil
}

func (m *ResponderRangeProof) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *ResponderRangeProof) GetS1() []byte {
	if m != nil {
		return m.S1
	}
	return nil
}

func (m *ResponderRangeProof) GetS2() []byte {
	if m != nil {
		return m.S2
	}
	return nil
}

func (m *ResponderRangeProof) GetT1() []byte {
	if m != nil {
		return m.T1
	}
	return nil
}

func (m *ResponderRangeProof) GetT2() []byte {
	if m != nil {
		return m.T2
	}
	return nil
}

func (m *ResponderRangeProof) GetXX() []byte {
	if m != nil {
		return m.XX
	}
	return nil
}

func (m *ResponderRangeProof) GetXY() []byte {
	if m != nil {
		return m.XY
	}
	return nil
}

type SchnorrProof struct {
	PubKey               []byte   `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Num                  []byte   `protobuf:"bytes,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchnorrProof) Reset()         { *m = SchnorrProof{} }
func (m *SchnorrProof) String() string { return proto.CompactTextString(m) }
func (*SchnorrProof) ProtoMessage()    {}
func (*SchnorrProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *SchnorrProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchnorrProof.Unmarshal(m, b)
}
func (m *SchnorrProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchnorrProof.Marshal(b, m, deterministic)
}
func (m *SchnorrProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchnorrProof.Merge(m, src)
}
func (m *SchnorrProof) XXX_Size() int {
	return xxx_messageInfo_SchnorrProof.Size(m)
}
func (m *SchnorrProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SchnorrProof.DiscardUnknown(m)
}

var xxx_messageInfo_SchnorrProof proto.InternalMessageInfo

func (m *SchnorrProof) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *SchnorrProof) GetNum() []byte {
	if m != nil {
		return m.Num
	}
	return nil
}

type SiProof struct {
	VX                   []byte   `protobuf:"bytes,1,opt,name=v_x,json=vX,proto3" json:"v_x,omitempty"`
	VY                   []byte   `protobuf:"bytes,2,opt,name=v_y,json=vY,proto3" json:"v_y,omitempty"`
	AX                   []byte   `protobuf:"bytes,3,opt,name=a_x,json=aX,proto3" json:"a_x,omitempty"`
	AY                   []byte   `protobuf:"bytes,4,opt,name=a_y,json=aY,proto3" json:"a_y,omitempty"`
	BX                   []byte   `protobuf:"bytes,5,opt,name=b_x,json=bX,proto3" json:"b_x,omitempty"`
	BY                   []byte   `protobuf:"bytes,6,opt,name=b_y,json=bY,proto3" json:"b_y,omitempty"`
	AlphaX               []byte   `protobuf:"bytes,7,opt,name=alpha_x,json=alphaX,proto3" json:"alpha_x,omitempty"`
	AlphaY               []byte   `protobuf:"bytes,8,opt,name=alpha_y,json=alphaY,proto3" json:"alpha_y,omitempty"`
	BetaX                []byte   `protobuf:"bytes,9,opt,name=beta_x,json=betaX,proto3" json:"beta_x,omitempty"`
	BetaY                []byte   `protobuf:"bytes,10,opt,name=beta_y,json=betaY,proto3" json:"beta_y,omitempty"`
	T                    []byte   `protobuf:"bytes,11,opt,name=t,proto3" json:"t,omitempty"`
	U                    []byte   `protobuf:"bytes,12,opt,name=u,proto3" json:"u,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiProof) Reset()         { *m = SiProof{} }
func (m *SiProof) String() string { return proto.CompactTextString(m) }
func (*SiProof) ProtoMessage()    {}
func (*SiProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *SiProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiProof.Unmarshal(m, b)
}
func (m *SiProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiProof.Marshal(b, m, deterministic)
}
func (m *SiProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiProof.Merge(m, src)
}
func (m *SiProof) XXX_Size() int {
	return xxx_messageInfo_SiProof.Size(m)
}
func (m *SiProof) XXX_DiscardUnknown() {
	xxx_messageInfo_SiProof.DiscardUnknown(m)
}

var xxx_messageInfo_SiProof proto.InternalMessageInfo

func (m *SiProof) GetVX() []byte {
	if m != nil {
		return m.VX
	}
	return nil
}

func (m *SiProof) GetVY() []byte {
	if m != nil {
		return m.VY
	}
	return nil
}

func (m *SiProof) GetAX() []byte {
	if m != nil {
		return m.AX
	}
	return nil
}

func (m *SiProof) GetAY() []byte {
	if m != nil {
		return m.AY
	}
	return nil
}

func (m *SiProof) GetBX() []byte {
	if m != nil {
		return m.BX
	}
	return nil
}

func (m *SiProof) GetBY() []byte {
	if m != nil {
		return m.BY
	}
	return nil
}

func (m *SiProof) GetAlphaX() []byte {
	if m != nil {
		return m.AlphaX
	}
	return nil
}

func (m *SiProof) GetAlphaY() []byte {
	if m != nil {
		return m.AlphaY
	}
	return nil
}

func (m *SiProof) GetBetaX() []byte {
	if m != nil {
		return m.BetaX
	}
	return nil
}

func (m *SiProof) GetBetaY() []byte {
	if m != nil {
		return m.BetaY
	}
	return nil
}

func (m *SiProof) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *SiProof) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

type SiCheck struct {
	U                    []byte   `protobuf:"bytes,1,opt,name=u,proto3" json:"u,omitempty"`
	T                    []byte   `protobuf:"bytes,2,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SiCheck) Reset()         { *m = SiCheck{} }
func (m *SiCheck) String() string { return proto.CompactTextString(m) }
func (*SiCheck) ProtoMessage()    {}
func (*SiCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *SiCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SiCheck.Unmarshal(m, b)
}
func (m *SiCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SiCheck.Marshal(b, m, deterministic)
}
func (m *SiCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SiCheck.Merge(m, src)
}
func (m *SiCheck) XXX_Size() int {
	return xxx_messageInfo_SiCheck.Size(m)
}
func (m *SiCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_SiCheck.DiscardUnknown(m)
}

var xxx_messageInfo_SiCheck proto.InternalMessageInfo

func (m *SiCheck) GetU() []byte {
	if m != nil {
		return m.U
	}
	return nil
}

func (m *SiCheck) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

type PQProof struct {
	Zi                   [][]byte `protobuf:"bytes,1,rep,name=zi,proto3" json:"zi,omitempty"`
	Xi                   [][]byte `protobuf:"bytes,2,rep,name=xi,proto3" json:"xi,omitempty"`
	Y                    []byte   `protobuf:"bytes,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PQProof) Reset()         { *m = PQProof{} }
func (m *PQProof) String() string { return proto.CompactTextString(m) }
func (*PQProof) ProtoMessage()    {}
func (*PQProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *PQProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PQProof.Unmarshal(m, b)
}
func (m *PQProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PQProof.Marshal(b, m, deterministic)
}
func (m *PQProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQProof.Merge(m, src)
}
func (m *PQProof) XXX_Size() int {
	return xxx_messageInfo_PQProof.Size(m)
}
func (m *PQProof) XXX_DiscardUnknown() {
	xxx_messageInfo_PQProof.DiscardUnknown(m)
}

var xxx_messageInfo_PQProof proto.InternalMessageInfo

func (m *PQProof) GetZi() [][]byte {
	if m != nil {
		return m.Zi
	}
	return nil
}

func (m *PQProof) GetXi() [][]byte {
	if m != nil {
		return m.Xi
	}
	return nil
}

func (m *PQProof) GetY() []byte {
	if m != nil {
		return m.Y
	}
	return nil
}

type KeyGenData struct {
	Label                string          `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	SignThreshold        uint64          `protobuf:"varint,2,opt,name=sign_threshold,json=signThreshold,proto3" json:"sign_threshold,omitempty"`
	Paras                []*ParameterMap `protobuf:"bytes,3,rep,name=paras,proto3" json:"paras,omitempty"`
	PubKeySum            []byte          `protobuf:"bytes,4,opt,name=pub_key_sum,json=pubKeySum,proto3" json:"pub_key_sum,omitempty"`
	KeyNodes             []string        `protobuf:"bytes,5,rep,name=key_nodes,json=keyNodes,proto3" json:"key_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *KeyGenData) Reset()         { *m = KeyGenData{} }
func (m *KeyGenData) String() string { return proto.CompactTextString(m) }
func (*KeyGenData) ProtoMessage()    {}
func (*KeyGenData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *KeyGenData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyGenData.Unmarshal(m, b)
}
func (m *KeyGenData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyGenData.Marshal(b, m, deterministic)
}
func (m *KeyGenData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyGenData.Merge(m, src)
}
func (m *KeyGenData) XXX_Size() int {
	return xxx_messageInfo_KeyGenData.Size(m)
}
func (m *KeyGenData) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyGenData.DiscardUnknown(m)
}

var xxx_messageInfo_KeyGenData proto.InternalMessageInfo

func (m *KeyGenData) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *KeyGenData) GetSignThreshold() uint64 {
	if m != nil {
		return m.SignThreshold
	}
	return 0
}

func (m *KeyGenData) GetParas() []*ParameterMap {
	if m != nil {
		return m.Paras
	}
	return nil
}

func (m *KeyGenData) GetPubKeySum() []byte {
	if m != nil {
		return m.PubKeySum
	}
	return nil
}

func (m *KeyGenData) GetKeyNodes() []string {
	if m != nil {
		return m.KeyNodes
	}
	return nil
}

type ParameterMap struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Share                *ShareXY `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	NTilde               []byte   `protobuf:"bytes,3,opt,name=n_tilde,json=nTilde,proto3" json:"n_tilde,omitempty"`
	H1                   []byte   `protobuf:"bytes,4,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   []byte   `protobuf:"bytes,5,opt,name=h2,proto3" json:"h2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParameterMap) Reset()         { *m = ParameterMap{} }
func (m *ParameterMap) String() string { return proto.CompactTextString(m) }
func (*ParameterMap) ProtoMessage()    {}
func (*ParameterMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *ParameterMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterMap.Unmarshal(m, b)
}
func (m *ParameterMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterMap.Marshal(b, m, deterministic)
}
func (m *ParameterMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterMap.Merge(m, src)
}
func (m *ParameterMap) XXX_Size() int {
	return xxx_messageInfo_ParameterMap.Size(m)
}
func (m *ParameterMap) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterMap.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterMap proto.InternalMessageInfo

func (m *ParameterMap) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ParameterMap) GetShare() *ShareXY {
	if m != nil {
		return m.Share
	}
	return nil
}

func (m *ParameterMap) GetNTilde() []byte {
	if m != nil {
		return m.NTilde
	}
	return nil
}

func (m *ParameterMap) GetH1() []byte {
	if m != nil {
		return m.H1
	}
	return nil
}

func (m *ParameterMap) GetH2() []byte {
	if m != nil {
		return m.H2
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyGenPhase1Msg)(nil), "types.KeyGenPhase1Msg")
	proto.RegisterType((*KeyGenPhase2Msg)(nil), "types.KeyGenPhase2Msg")
	proto.RegisterType((*KeyGenPhase3Msg)(nil), "types.KeyGenPhase3Msg")
	proto.RegisterType((*KeySignPhase1Msg)(nil), "types.KeySignPhase1Msg")
	proto.RegisterType((*KeySignPhase2Msg)(nil), "types.KeySignPhase2Msg")
	proto.RegisterType((*KeySignPhase3And4Msg)(nil), "types.KeySignPhase3And4Msg")
	proto.RegisterType((*KeySignPhase5AMsg)(nil), "types.KeySignPhase5AMsg")
	proto.RegisterType((*KeySignPhase5BMsg)(nil), "types.KeySignPhase5BMsg")
	proto.RegisterType((*KeySignPhase5CMsg)(nil), "types.KeySignPhase5CMsg")
	proto.RegisterType((*KeySignPhase5DMsg)(nil), "types.KeySignPhase5DMsg")
	proto.RegisterType((*KeySignPhase5EMsg)(nil), "types.KeySignPhase5EMsg")
	proto.RegisterType((*SigR)(nil), "types.SigR")
	proto.RegisterType((*ShareXY)(nil), "types.ShareXY")
	proto.RegisterType((*PaillierPubKey)(nil), "types.PaillierPubKey")
	proto.RegisterType((*InitiatorRangeProof)(nil), "types.InitiatorRangeProof")
	proto.RegisterType((*ResponderRangeProof)(nil), "types.ResponderRangeProof")
	proto.RegisterType((*SchnorrProof)(nil), "types.SchnorrProof")
	proto.RegisterType((*SiProof)(nil), "types.SiProof")
	proto.RegisterType((*SiCheck)(nil), "types.SiCheck")
	proto.RegisterType((*PQProof)(nil), "types.PQProof")
	proto.RegisterType((*KeyGenData)(nil), "types.KeyGenData")
	proto.RegisterType((*ParameterMap)(nil), "types.ParameterMap")
}

func init() {
	proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355)
}

var fileDescriptor_d938547f84707355 = []byte{
	// 1277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0xed, 0xfc, 0x9e, 0xb8, 0xe9, 0xd6, 0xdb, 0x16, 0x17, 0x54, 0x58, 0xac, 0x56, 0x5a,
	0x24, 0xba, 0xab, 0x4d, 0x41, 0x88, 0x1b, 0xa4, 0xfe, 0x50, 0x84, 0x56, 0x6d, 0x83, 0xdb, 0x8b,
	0x84, 0x1b, 0x6b, 0x9c, 0xcc, 0xda, 0xa3, 0xc4, 0x76, 0xf0, 0x8c, 0xd3, 0x38, 0xb7, 0xf0, 0x0e,
	0xbc, 0x00, 0xb7, 0x5c, 0xf0, 0x1a, 0xe5, 0x51, 0xb8, 0xe5, 0x01, 0xd0, 0xfc, 0x25, 0x76, 0xd8,
	0xb6, 0x81, 0xde, 0xf9, 0x7c, 0xe7, 0xcc, 0xcc, 0x37, 0xdf, 0x39, 0x33, 0x3e, 0x03, 0x3d, 0x56,
	0x2e, 0x30, 0x3d, 0x59, 0xe4, 0x19, 0xcb, 0x9c, 0xa6, 0x30, 0xbc, 0x5f, 0x4c, 0xb8, 0x7a, 0x8e,
	0xcb, 0xef, 0x70, 0x3a, 0x8c, 0x11, 0xc5, 0x67, 0x4f, 0x69, 0xe4, 0xdc, 0x06, 0x98, 0xa3, 0x10,
	0xcf, 0x83, 0x8b, 0x3c, 0x4b, 0x5c, 0xe3, 0xc8, 0x38, 0xee, 0xfa, 0x5d, 0x81, 0x3c, 0xc9, 0xb3,
	0xc4, 0xb9, 0x03, 0xfd, 0x45, 0x11, 0x06, 0x33, 0x5c, 0x06, 0x93, 0x2c, 0x49, 0x08, 0x73, 0xcd,
	0x23, 0xe3, 0xd8, 0xf6, 0xed, 0x45, 0x11, 0x9e, 0xe3, 0xf2, 0x91, 0xc0, 0xf8, 0x24, 0x93, 0xec,
	0x42, 0x47, 0x58, 0x47, 0xd6, 0xb1, 0xed, 0x77, 0x27, 0xd9, 0x85, 0x72, 0xdf, 0x84, 0xd6, 0xb3,
	0x97, 0x64, 0x3e, 0xc5, 0x6e, 0x43, 0x0c, 0x56, 0x96, 0xd3, 0x07, 0x33, 0x3e, 0x73, 0x9b, 0x02,
	0x33, 0xe3, 0x33, 0x61, 0x0f, 0xdc, 0x96, 0xb2, 0x07, 0xce, 0x1d, 0x68, 0x2e, 0xf2, 0x2c, 0xbb,
	0x70, 0xdb, 0x47, 0xc6, 0x71, 0x6f, 0xd0, 0x3f, 0x91, 0x7b, 0x1a, 0xfe, 0x30, 0xe4, 0xa8, 0x2f,
	0x9d, 0xce, 0x29, 0x5c, 0xa7, 0x31, 0x4a, 0x48, 0x1e, 0xd0, 0x18, 0xe5, 0x38, 0x50, 0x7c, 0xdd,
	0x8e, 0x98, 0xe7, 0x9a, 0xf4, 0xbd, 0xe0, 0xae, 0xa1, 0xe0, 0xec, 0xfd, 0x6e, 0xd4, 0x64, 0x18,
	0xec, 0x21, 0xc3, 0x2d, 0xe8, 0x48, 0x37, 0xcb, 0x84, 0x00, 0x5d, 0xbf, 0x2d, 0xec, 0x97, 0x19,
	0x27, 0x29, 0xd6, 0x75, 0xad, 0x1a, 0x49, 0xb1, 0xe0, 0x68, 0xec, 0x4b, 0xa7, 0xf3, 0x01, 0xb4,
	0x35, 0x2f, 0xa5, 0x81, 0x14, 0xd0, 0xf9, 0x14, 0xec, 0x70, 0x4e, 0xd2, 0x69, 0x70, 0x81, 0x26,
	0x2c, 0xcb, 0x95, 0x1a, 0x3d, 0x81, 0x3d, 0x11, 0x90, 0xb7, 0xae, 0xd1, 0xbd, 0xbf, 0x07, 0xdd,
	0xdb, 0x00, 0x4a, 0x92, 0x45, 0x11, 0xaa, 0x8c, 0x75, 0x25, 0x32, 0x2c, 0x42, 0xe7, 0x33, 0xad,
	0xab, 0xa4, 0x7c, 0xa8, 0x29, 0x4f, 0xe2, 0x34, 0xcb, 0xf3, 0xaa, 0xb8, 0xde, 0xaf, 0x16, 0x1c,
	0x9c, 0xe3, 0xf2, 0x05, 0x89, 0xf6, 0xaf, 0x99, 0xb7, 0x88, 0xf5, 0x11, 0x74, 0x13, 0x4c, 0x29,
	0x8a, 0x70, 0x30, 0x13, 0xab, 0xdb, 0x7e, 0x47, 0x01, 0xe7, 0x55, 0x67, 0xae, 0x54, 0xd2, 0x4e,
	0xdf, 0xb9, 0x07, 0x87, 0x94, 0x44, 0x41, 0xc6, 0x62, 0x9c, 0xd3, 0x20, 0xd7, 0xb5, 0x26, 0xe5,
	0x3a, 0xa0, 0x24, 0x7a, 0x2e, 0x3c, 0xbe, 0x2a, 0xb9, 0x6f, 0xe0, 0xea, 0x02, 0x91, 0xf9, 0x9c,
	0x60, 0xa1, 0xc1, 0x39, 0x2e, 0x45, 0x5d, 0xf5, 0x06, 0x37, 0x74, 0x11, 0x29, 0xaf, 0xac, 0x09,
	0xbf, 0xbf, 0xa8, 0xd9, 0xce, 0x73, 0xb8, 0xb9, 0x19, 0x9f, 0xa3, 0x34, 0xc2, 0x81, 0xd0, 0x23,
	0x98, 0xa9, 0x5a, 0xfc, 0x50, 0x4d, 0xf3, 0x7d, 0x4a, 0x18, 0x41, 0x2c, 0xcb, 0x7d, 0x1e, 0x24,
	0xa5, 0x3b, 0xd4, 0x23, 0xb7, 0xd8, 0xf9, 0x1b, 0x27, 0xcc, 0x45, 0x9d, 0xfe, 0xe7, 0x09, 0x7d,
	0xef, 0xb5, 0x59, 0xcf, 0xcc, 0x7b, 0x96, 0xf1, 0xe7, 0xe0, 0x6c, 0x32, 0x13, 0xe4, 0x98, 0x2e,
	0xb2, 0x94, 0x62, 0x95, 0xa2, 0x03, 0x9d, 0x22, 0x5f, 0xe1, 0xd5, 0xe8, 0x7c, 0x1b, 0xdd, 0xa8,
	0x45, 0xfb, 0x9b, 0xe8, 0x37, 0x8b, 0xd9, 0xac, 0xed, 0x5d, 0x0e, 0x98, 0xe2, 0xf7, 0x10, 0xb3,
	0xf5, 0x7f, 0x26, 0xf4, 0xbd, 0x3f, 0x0d, 0xb8, 0x5e, 0x15, 0xf3, 0xfe, 0x83, 0x74, 0xfa, 0xc5,
	0x1e, 0x82, 0x3a, 0xd0, 0x60, 0x31, 0x46, 0xea, 0x88, 0x89, 0x6f, 0xe7, 0x04, 0x3a, 0x33, 0x12,
	0xbc, 0xf3, 0x80, 0xb5, 0x67, 0x44, 0x7c, 0x38, 0xf7, 0xc0, 0xae, 0x56, 0xb6, 0x50, 0xb1, 0x37,
	0xe8, 0xe9, 0x31, 0x24, 0xf2, 0x7d, 0xd8, 0xd6, 0xf7, 0x3e, 0x17, 0xc6, 0xcf, 0x06, 0x5c, 0xab,
	0xee, 0xe6, 0xcb, 0x07, 0xfb, 0xd5, 0xc6, 0xb2, 0x7e, 0xc7, 0xb7, 0x97, 0xea, 0x30, 0xdd, 0x82,
	0x0e, 0xda, 0x5e, 0xee, 0xc2, 0x85, 0xb6, 0xae, 0x50, 0xbb, 0x64, 0xfa, 0xdb, 0xa1, 0x74, 0x79,
	0xaf, 0x77, 0x59, 0x3c, 0xdc, 0xeb, 0x7f, 0xa3, 0xae, 0x26, 0xb3, 0x7e, 0x9b, 0x92, 0xda, 0x95,
	0x7f, 0x07, 0xfa, 0xcb, 0xa0, 0xa6, 0x82, 0xa4, 0x65, 0x2f, 0x1f, 0x6e, 0x65, 0xe0, 0x51, 0xa8,
	0x1e, 0x25, 0x19, 0xda, 0x68, 0x27, 0x2a, 0x0c, 0x2e, 0x51, 0xd4, 0x0e, 0x2b, 0x51, 0x5e, 0xbc,
	0xb3, 0x97, 0x47, 0xfb, 0x29, 0x5a, 0xec, 0x28, 0x5a, 0x6c, 0x65, 0x63, 0x3b, 0x8a, 0x32, 0x25,
	0xdb, 0x6f, 0xbb, 0xb2, 0x3d, 0xde, 0x4f, 0xb6, 0x49, 0x8c, 0x27, 0xb3, 0x7f, 0xc9, 0xf6, 0x88,
	0xa3, 0xbe, 0x74, 0xf2, 0xad, 0x16, 0x97, 0xca, 0x56, 0xec, 0x08, 0xc2, 0x2e, 0x95, 0x8d, 0xbd,
	0x4d, 0x90, 0x6f, 0xf7, 0x3b, 0x2d, 0x94, 0x44, 0xb9, 0x3e, 0x2d, 0xfc, 0x5b, 0x61, 0x54, 0x31,
	0x11, 0xdf, 0x8e, 0x0d, 0xc6, 0x52, 0x2d, 0x6a, 0x2c, 0x3d, 0x0f, 0x1a, 0xfc, 0x10, 0x70, 0x74,
	0x25, 0xe6, 0xb4, 0x7d, 0x63, 0xc5, 0xad, 0x52, 0x4d, 0x64, 0x94, 0xde, 0x5d, 0x68, 0xab, 0x1f,
	0xee, 0x5b, 0xc3, 0x86, 0xd0, 0xaf, 0xdf, 0xfb, 0xce, 0x01, 0x58, 0x73, 0x9c, 0x8a, 0x78, 0xcb,
	0xe7, 0x9f, 0x7c, 0x44, 0xaa, 0x47, 0x08, 0x2b, 0x52, 0xdc, 0x8c, 0x88, 0x47, 0xa7, 0xf4, 0x27,
	0x45, 0x8d, 0x7f, 0x7a, 0x19, 0x1c, 0x5e, 0x72, 0x63, 0xf3, 0x61, 0x6b, 0x4d, 0x62, 0xcd, 0xad,
	0x57, 0x7a, 0xca, 0x57, 0xbc, 0xcb, 0x49, 0x0a, 0x35, 0xa7, 0x99, 0x14, 0xdc, 0x4b, 0xf5, 0x6e,
	0x29, 0xf7, 0xd2, 0x4d, 0x4f, 0x44, 0x45, 0x4f, 0x44, 0x37, 0x3d, 0x11, 0x1d, 0x78, 0x7f, 0x1b,
	0x70, 0x78, 0xc9, 0xb5, 0xe6, 0x5c, 0x83, 0x46, 0x52, 0x04, 0x7a, 0xe7, 0x56, 0x52, 0x8c, 0x14,
	0xa4, 0xb7, 0x6f, 0x25, 0xc5, 0x58, 0xf2, 0xb2, 0x34, 0xaf, 0xab, 0x60, 0xad, 0x83, 0xa9, 0x5a,
	0xdb, 0x5c, 0x3f, 0xe6, 0x6e, 0xfd, 0x4b, 0x35, 0x98, 0x4c, 0x43, 0x4b, 0xa5, 0x41, 0x6e, 0xa2,
	0xad, 0x37, 0x21, 0x48, 0x77, 0xea, 0xa4, 0xbb, 0x3b, 0xa4, 0x41, 0x93, 0xe6, 0x36, 0x3b, 0x73,
	0x7b, 0xd2, 0x66, 0xc2, 0xcf, 0x06, 0xae, 0xad, 0xec, 0x01, 0x27, 0xb2, 0x0a, 0x56, 0xee, 0x15,
	0x09, 0xac, 0x46, 0x12, 0x28, 0xdd, 0xbe, 0x02, 0xc6, 0xde, 0xd7, 0x60, 0x57, 0x6f, 0xcf, 0x6a,
	0x3f, 0x65, 0xd4, 0xfa, 0x29, 0x9e, 0xa2, 0x22, 0xd1, 0x7b, 0x4e, 0x8b, 0xc4, 0xfb, 0xcb, 0x80,
	0xb6, 0xba, 0x3f, 0xf8, 0xbc, 0xcb, 0x8d, 0x48, 0xe6, 0x72, 0x24, 0x01, 0x2d, 0x91, 0xb9, 0x1c,
	0x73, 0x00, 0x05, 0x2b, 0x9d, 0x1e, 0x34, 0x92, 0x80, 0xee, 0xda, 0x4c, 0x24, 0x22, 0xc2, 0x60,
	0xa5, 0x53, 0x14, 0x8e, 0x24, 0x50, 0xea, 0x1c, 0x85, 0x63, 0x4e, 0x0e, 0xcd, 0x17, 0x31, 0x9f,
	0x47, 0x0a, 0xd6, 0x12, 0xe6, 0x68, 0xeb, 0xd0, 0xdd, 0xa9, 0x74, 0x8c, 0x9d, 0x1b, 0xd0, 0x0a,
	0x31, 0xe3, 0x03, 0xa4, 0x88, 0x4d, 0x6e, 0x8d, 0x36, 0x70, 0xa9, 0xb4, 0x14, 0xf0, 0x58, 0xa6,
	0xa9, 0x57, 0x49, 0x53, 0xa1, 0xb4, 0x34, 0x0a, 0x71, 0x12, 0xe4, 0xa9, 0x97, 0x0e, 0x55, 0x84,
	0x85, 0x1c, 0xa4, 0x8a, 0x90, 0x79, 0x5f, 0x41, 0x5b, 0xb5, 0xd1, 0x3c, 0x19, 0x6b, 0xe2, 0x1a,
	0xa2, 0x69, 0x37, 0xd7, 0x84, 0xdb, 0x2b, 0xe2, 0x9a, 0xd2, 0x5e, 0x11, 0x79, 0x84, 0x2c, 0x7d,
	0x84, 0xfe, 0x30, 0x00, 0x64, 0x37, 0xfa, 0x18, 0x31, 0xe4, 0x5c, 0x87, 0xa6, 0x38, 0xdf, 0xea,
	0xb0, 0x4b, 0xc3, 0xb9, 0x0b, 0x7d, 0x4a, 0xa2, 0x34, 0x60, 0x71, 0x8e, 0x69, 0x9c, 0xcd, 0xa7,
	0x62, 0xe1, 0x86, 0x7f, 0x85, 0xa3, 0x2f, 0x35, 0x28, 0xfa, 0x50, 0x94, 0x23, 0x2a, 0x5e, 0x0c,
	0xdb, 0xdf, 0xe4, 0x10, 0xe5, 0x28, 0xc1, 0x0c, 0xe7, 0x4f, 0xd1, 0xc2, 0x97, 0x11, 0xce, 0xc7,
	0xd0, 0xd3, 0xef, 0x10, 0x5a, 0x24, 0x2a, 0x1b, 0x5d, 0x99, 0xf3, 0x17, 0x45, 0xc2, 0x7b, 0x47,
	0xee, 0x4b, 0xb3, 0x29, 0xa6, 0x6e, 0xf3, 0xc8, 0x3a, 0xee, 0xfa, 0x9d, 0x19, 0x2e, 0x9f, 0x71,
	0x9b, 0xff, 0x0f, 0xed, 0xea, 0xa4, 0x6f, 0x60, 0xbd, 0xe9, 0xe4, 0xcd, 0x77, 0x74, 0xf2, 0x69,
	0xc0, 0xc4, 0x6b, 0x46, 0x8a, 0xd2, 0x4a, 0xab, 0xaf, 0x99, 0xc6, 0xce, 0x6b, 0x46, 0xbf, 0x6e,
	0x06, 0x0f, 0x3f, 0xf9, 0xf1, 0x76, 0x44, 0xd8, 0x49, 0x18, 0xe3, 0xd5, 0x09, 0xc9, 0x4e, 0x27,
	0x31, 0x22, 0xe9, 0xe9, 0x94, 0x2b, 0x72, 0x2a, 0x16, 0x0a, 0x5b, 0xe2, 0xb1, 0x76, 0xff, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xd2, 0xce, 0x8e, 0xbb, 0x0d, 0x00, 0x00,
}
